baseURL = 'https://catboy.it/'
languageCode = 'en-us'
title = 'catboy.it'
theme = 'custom'

[markup.goldmark.renderer]
unsafe = true

[params]
[params.author]
name = 'addr2vio'


[menus]
[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 20

[[menus.main]]
name = 'Writeups'
pageRef = '/writeups'
weight = 30
